logic2j Design ideas
====================
:toc:
:toclevels: 4


Requirements for the API for solutions
--------------------------------------

>>>> IDEAS AND WORK IN PROGRESS - THIS IS NOT A DOCUMENTATION! <<<<

Proposal: this API will leverage state-of-the-art design:
* fluent
* lazy (like "streams": evaluation is delayed to the latest moment so that the minimal operations will be executed)
* type-strong using generics
* either server-push (Inversion of Control) or client-pull (iterator)
* compatible with foreach and Iterable


Requirement: this API must be really re-entrant and context-free, it may be called:
* by a client of the engine,
* from within a prolog-implemented primitive
* from within a solution callback when trying to solve a sub-goal



=== UC 1: determine presence vs absence, or single vs multiple nature of solution to a goal, be able to assert

    solve(goal).exists()          -> true when there's at least one solution (will solve only first)
    solve(goal).count()           -> number of solutions (will solve all but not bind any solution to variables!)
    solve(goal).first()           -> first solution or null if none, silent if more than one
    solve(goal).unique()          -> only solution expected: Exception if none or more than one



=== UC 2: access whole solution to goals

    solve(goal).solution()...
    solve(goal).solution().unique()    -> if you expect only one
    solve(goal).iterator().list()      -> if multiple are expected

(note: result of solution() is an Iterable<Object>)  (usually Object is a Struct)



=== UC 3: access values(s) bound to a particular variable

    solve("chr(a,Y)").var("Y").unique()    -> 97
    solve("chr(C,X)").var("X").list()      -> list of bindings



=== UC 4: access all values

    solve("chr(X,Y)").vars().list()




Requirements and wishlist for logic2j's Term API
------------------------------------------------


Parsing of terms:
-----------------

Features for converting things into Terms hierarchies:

. Type conversion      (eg. BigDecimal to Long, StringBuilder to Struct, Java Collection to Prolog list)
. Interpretation       (eg. "x" is an atom, "X" is a variable)
. Operators            (eg. a:-b is ':-'(a,b), [a,b] is ".(a,.(b,[]))"
. Normalization        (unique Variables, common subtrees factorized, etc)
. Primitives           (eg. "true", "!" are actually not atoms but primitives)

From the most basic conversion to the most evolved

.. new Struct(functor, args...)
.. Struct.createPList()
.. Struct.valueOf(functor, args...)
.  TermApi.valueOf(Object)
.  TermUnmarshaller.unmarshall()





>>>> IDEAS AND WORK IN PROGRESS - THIS IS NOT A DOCUMENTATION! <<<<

UC 1: make sure term is fully ground (no more free Vars anywhere) and obtain resolved solution.

   binding("X").isGround()
   binding("X").isFullyGround()
   binding("X").resolved()

